# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c74d260b20a2ddc538ff850b6f39724dff1321fd87e167ff9c720f71c5833269284d9cc4201c1a8f1df6e030af4833bf95c94675d066beb74f91b0389b84fdf8

test:
  secret_key_base: 369edd68d569ab9151dd16e4477a223857f50c3bb47e47d63e504bbda21737485793e7c3bb5998f3aa19f8e48347a57e2a753a034a7eb34215dd478586ae6ec8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
